<?php
require_once __DIR__ . '/includes/db.php';
require_once __DIR__ . '/includes/functions.php';

$token = $_GET['token'] ?? '';

if (!$token) {
    die("<h2 style='color:red;text-align:center'>Invalid verification link</h2>");
}

// Fetch report
$stmt = $pdo->prepare("SELECT * FROM report_verifications WHERE token = ?");
$stmt->execute([$token]);
$report = $stmt->fetch(PDO::FETCH_ASSOC);

// Log verification safely (no duplicate crash)
$ip = $_SERVER['REMOTE_ADDR'] ?? 'UNKNOWN';
$stmtLog = $pdo->prepare("
    INSERT INTO verification_logs (token, ip_address, verified_at)
    VALUES (?, ?, NOW())
    ON DUPLICATE KEY UPDATE 
        ip_address = VALUES(ip_address),
        verified_at = NOW()
");
$stmtLog->execute([$token, $ip]);
?>

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Nexus Bank — Receipt Verification</title>

<style>
body {
    margin:0;
    background:#0f172a;
    font-family: 'Segoe UI', sans-serif;
    color:#e5e7eb;
}

.container {
    min-height:100vh;
    display:flex;
    justify-content:center;
    align-items:center;
}

.card {
    width:520px;
    background:rgba(15,23,42,.85);
    border-radius:18px;
    padding:35px;
    box-shadow:0 0 40px rgba(56,189,248,.25);
    border:1px solid rgba(56,189,248,.3);
}

.header {
    text-align:center;
    margin-bottom:20px;
}

.header h1 {
    margin:0;
    font-size:22px;
    letter-spacing:1px;
}

.status-ok {
    color:#22c55e;
    font-size:22px;
    text-align:center;
    margin:18px 0;
}

.status-bad {
    color:#ef4444;
    font-size:22px;
    text-align:center;
    margin:18px 0;
}

.row {
    margin:10px 0;
}

.label {
    color:#94a3b8;
    font-size:13px;
}

.value {
    font-weight:600;
    word-break:break-all;
}

.footer {
    margin-top:25px;
    text-align:center;
    font-size:12px;
    color:#94a3b8;
    border-top:1px solid rgba(148,163,184,.25);
    padding-top:15px;
}

.seal {
    color:#38bdf8;
    letter-spacing:2px;
    font-size:11px;
}

.signature {
    margin-top:6px;
}
</style>
</head>

<body>

<div class="container">
<div class="card">

<div class="header">
    <h1>NEXUS BANK — RECEIPT VERIFICATION</h1>
</div>

<?php if($report): ?>

<div class="status-ok">✔ RECEIPT VERIFIED</div>

<div class="row"><span class="label">Verification Token</span><br><span class="value"><?= htmlspecialchars($report['token']) ?></span></div>
<div class="row"><span class="label">Report Type</span><br><span class="value"><?= htmlspecialchars($report['report_type']) ?></span></div>
<div class="row"><span class="label">Generated By (Admin ID)</span><br><span class="value"><?= htmlspecialchars($report['admin_id']) ?></span></div>
<div class="row"><span class="label">Generated On</span><br><span class="value"><?= htmlspecialchars($report['created_at']) ?></span></div>

<?php else: ?>

<div class="status-bad">✖ INVALID OR FAKE RECEIPT</div>

<?php endif; ?>

<div class="footer">
    <div class="seal">SECURE DIGITAL SEAL</div>
    <div class="signature">
        Authorized & Certified by  
        <strong>Nexus Bank Verification Authority</strong>
    </div>
</div>

</div>
</div>

</body>
</html>
