<?php
session_start();

require_once '../includes/db.php';
require_once '../includes/functions.php';
require_once '../vendor/tecnickcom/tcpdf/tcpdf.php';
require_once '../vendor/autoload.php';

use Endroid\QrCode\QrCode;
use Endroid\QrCode\Writer\PngWriter;

redirectIfNotAdmin();

logAdminAction(
    $pdo,
    $_SESSION['user_id'],
    'Report Download',
    'Downloaded transaction report Pdf'
);


$from    = $_GET['from_date'] ?? null;
$to      = $_GET['to_date'] ?? null;
$user_id = $_GET['user_id'] ?? null;

if (!$from || !$to) die("Invalid date range.");

class PDF extends TCPDF {
    public function Header() {
        $this->SetAlpha(0.06);
        $w = $this->getPageWidth();
        $h = $this->getPageHeight();
        $this->Image('../assets/images/LOGO-RECEIPT.png', ($w-140)/2, ($h-140)/2, 140);
        $this->SetAlpha(1);
    }

    public function Footer() {
        $this->SetY(-15);
        $this->SetFont('helvetica','I',8);
        $this->Cell(0,10,'CONFIDENTIAL | Generated '.date('Y-m-d H:i').' | Page '.$this->getAliasNumPage().'/'.$this->getAliasNbPages(),0,0,'C');
    }
}

$pdf = new PDF('L');
$pdf->SetMargins(10,20,10);
$pdf->SetAutoPageBreak(true,15);

/* === TOKEN + QR === */
$token = bin2hex(random_bytes(32));

// Always generate unique verification id
$verification_id = random_int(1000000000, 9999999999);

$insert = $pdo->prepare("
    INSERT INTO report_verifications 
    (verification_id, token, report_type, admin_id, created_at)
    VALUES (?, ?, 'admin_report', ?, NOW())
");
$insert->execute([$verification_id, $token, $_SESSION['user_id']]);


$verifyUrl = "http://localhost/Nexus-Banksystem/verify-report.php?token=" . urlencode($token);

$qr = QrCode::create($verifyUrl)->setSize(140);
$writer = new PngWriter();
$qrData = $writer->write($qr)->getString();

$qrFile = '../assets/qr/'.$token.'.png';
if(!is_dir('../assets/qr')) mkdir('../assets/qr',0777,true);
file_put_contents($qrFile,$qrData);

/* === PAGE === */
$pdf->AddPage();

$headerTop = 10;

/* Logo */
$pdf->Image('../assets/images/LOGO-RECEIPT.png', 12, $headerTop+5, 28);

// 🔒 Compact QR + Verification Block (fits inside divider)
$qrSize = 20;
$qrX = 258;
$qrY = 14;

$pdf->Image($qrFile, $qrX, $qrY, $qrSize);

// Verification text under QR
$pdf->SetFont('helvetica','',7);
$pdf->SetXY($qrX - 4, $qrY + $qrSize + 1);
$pdf->Cell($qrSize + 8, 3, 'Verification ID', 0, 2, 'C');

$pdf->SetFont('courier','B',7);
$pdf->Cell($qrSize + 8, 3, substr($token,0,16), 0, 2, 'C');


/* =======================
   TITLES
======================= */



/* Title */
$pdf->SetFont('dejavusans','B',15);
$pdf->SetXY(0,$headerTop+4);
$pdf->Cell(0,8,'NEXUS BANKING SYSTEM – TRANSACTION REPORT',0,1,'C');

/* Filters */
$pdf->SetFont('dejavusans','',10);
$pdf->SetXY(0,$headerTop+13);
$pdf->Cell(0,6,"From: $from    To: $to".($user_id?" | User ID: $user_id":" | All Users"),0,1,'C');

/* FOOTER */
$pdf->SetFont('dejavusans','I',9);
$pdf->SetTextColor(80,80,80);
$pdf->SetXY(0, $headerTop + 20);
$pdf->Cell(0, 5, "Generated by Nexus Bank — Secure Transaction Report", 0, 1, 'C');
$pdf->SetTextColor(0,0,0);


/* Divider line — LOCKED POSITION */
$dividerY = 45;
$pdf->Line(10, $dividerY, 287, $dividerY);
$pdf->SetY($dividerY + 4);

/* === DATA === */
$sql = "
SELECT t.transaction_id,u.user_id,u.full_name,u.email,t.type,t.amount,t.description,
COALESCE(ra.account_number,'N/A') related_account,t.created_at
FROM transactions t
JOIN accounts a ON t.account_id=a.account_id
JOIN users u ON a.user_id=u.user_id
LEFT JOIN accounts ra ON t.related_account_id=ra.account_id
WHERE DATE(t.created_at) BETWEEN :from AND :to";

$params=[":from"=>$from,":to"=>$to];
if($user_id){$sql.=" AND u.user_id=:uid";$params[":uid"]=$user_id;}

$stmt=$pdo->prepare($sql);
$stmt->execute($params);

/* === TABLE (RESTORED THEME) === */
$html = '
<table border="1" cellpadding="5">
<tr style="background-color:#1F2937;color:#fff;font-weight:bold;">
<th width="4%">#</th>
<th width="6%">ID</th>
<th width="7%">User</th>
<th width="11%">Name</th>
<th width="15%">Email</th>
<th width="8%">Type</th>
<th width="8%">Amount</th>
<th width="21%">Description</th>
<th width="10%">Account</th>
<th width="10%">Date</th>
</tr>';

$sn=1;
while($r=$stmt->fetch()){
$html.="<tr>
<td>$sn</td>
<td>{$r['transaction_id']}</td>
<td>{$r['user_id']}</td>
<td>{$r['full_name']}</td>
<td>{$r['email']}</td>
<td>{$r['type']}</td>
<td>₹".number_format($r['amount'],2)."</td>
<td>{$r['description']}</td>
<td>{$r['related_account']}</td>
<td>".date('Y-m-d H:i',strtotime($r['created_at']))."</td>
</tr>";
$sn++;
}
$html.="</table>";

$pdf->writeHTML($html,true,false,true,false,'');

/* === FOOTER NOTES === */

$pdf->SetY(-40);
$pdf->SetFont('helvetica','I',9);
$pdf->SetDrawColor(180,180,180);
$pdf->Line(10, $pdf->GetY(), 287, $pdf->GetY());

$pdf->Ln(4);
$pdf->MultiCell(0,6,
    "This document is system-generated by Nexus Bank and is digitally verifiable.\n".
    "Scan the QR code or visit the verification portal with the Verification ID shown above.\n".
    "Unauthorized modification invalidates this report.",
    0,'C'
);


/* === OUTPUT === */
$pdf->Output('transaction_report.pdf','D');
@unlink($qrFile);
exit;
