<?php
session_start();

require_once '../includes/db.php';
require_once '../includes/functions.php';
require_once '../vendor/tecnickcom/tcpdf/tcpdf.php';
require_once '../vendor/autoload.php';

use Endroid\QrCode\QrCode;
use Endroid\QrCode\Writer\PngWriter;

/* =======================
   USER AUTH
======================= */
redirectIfNotLoggedIn();

$userId = $_SESSION['user_id'];

$from = $_GET['date_from'] ?? '';
$to   = $_GET['date_to']   ?? '';

if(!$from || !$to) die("Invalid date range.");

/* =======================
   PDF CLASS
======================= */
class PDF extends TCPDF {

    public function Header() {
        $this->SetAlpha(0.06);
        $w = $this->getPageWidth();
        $h = $this->getPageHeight();
        $this->Image('../assets/images/LOGO-RECEIPT.png', ($w-140)/2, ($h-140)/2, 140);
        $this->SetAlpha(1);
    }

    public function Footer() {
        $this->SetY(-15);
        $this->SetFont('dejavusans','I',8);
        $this->Cell(0,10,'CONFIDENTIAL | Generated '.date('Y-m-d H:i').' | Page '.$this->getAliasNumPage().'/'.$this->getAliasNbPages(),0,0,'C');
    }
}

/* =======================
   INIT PDF
======================= */
$pdf = new PDF('L');

$pdf->setFontSubsetting(true);
$pdf->SetFont('dejavusans','',9,'',true);
$pdf->SetMargins(10,20,10);
$pdf->SetAutoPageBreak(true,15);

/* =======================
   TOKEN + QR
======================= */
$token = bin2hex(random_bytes(32));

// Generate unique verification ID
$verification_id = random_int(1000000000, 9999999999);

$insert = $pdo->prepare("
    INSERT INTO report_verifications 
    (verification_id, token, report_type, admin_id, created_at)
    VALUES (?, ?, 'user_receipt', ?, NOW())
");
$insert->execute([$verification_id, $token, $userId]);

$verifyUrl = "http://localhost/Nexus-Banksystem/verify-report.php?token=" . urlencode($token);

$qr = QrCode::create($verifyUrl)->setSize(140);
$writer = new PngWriter();
$qrData = $writer->write($qr)->getString();

$qrFile = '../assets/qr/'.$token.'.png';
if(!is_dir('../assets/qr')) mkdir('../assets/qr',0777,true);
file_put_contents($qrFile,$qrData);

/* =======================
   PAGE HEADER
======================= */
$pdf->AddPage();

$headerTop = 10;
$pdf->Image('../assets/images/LOGO-RECEIPT.png', 12, $headerTop+5, 28);

$qrSize = 20;
$qrX = 258;
$qrY = 14;

/* Title above QR */
$pdf->SetFont('dejavusans','B',8);
$pdf->SetXY($qrX - 4, $qrY - 6);
$pdf->Cell($qrSize + 8, 4, 'SCAN TO VERIFY', 0, 0, 'C');

/* QR image */
$pdf->Image($qrFile, $qrX, $qrY, $qrSize);

/* Verification label */
$pdf->SetFont('dejavusans','',7);
$pdf->SetXY($qrX - 4, $qrY + $qrSize + 1);
$pdf->Cell($qrSize + 8, 3, 'Verification ID', 0, 2, 'C');

/* Token value */
$pdf->SetFont('dejavusans','B',7);
$pdf->Cell($qrSize + 8, 3, substr($token,0,16), 0, 2, 'C');


/* =======================
   TITLES
======================= */
$pdf->SetFont('dejavusans','B',15);
$pdf->SetXY(0,$headerTop+4);
$pdf->Cell(0,8,'NEXUS BANKING SYSTEM – TRANSACTION RECEIPT',0,1,'C');

$pdf->SetFont('dejavusans','',10);
$pdf->SetXY(0,$headerTop+13);
$pdf->Cell(0,6,"From: $from    To: $to | User ID: $userId",0,1,'C');

$pdf->SetFont('dejavusans','I',9);
$pdf->SetXY(0, $headerTop + 20);
$pdf->Cell(0, 5, "Generated by Nexus Bank — Secure Transaction Receipt", 0, 1, 'C');

/* =======================
   DIVIDER
======================= */
$dividerY = 45;
$pdf->Line(10, $dividerY, 287, $dividerY);
$pdf->SetY($dividerY + 4);


/* =======================
   FETCH DATA
======================= */
$stmt = $pdo->prepare("
SELECT t.transaction_id, t.type, t.amount, t.description,
COALESCE(ra.account_number,'N/A') related_account, t.created_at
FROM transactions t
JOIN accounts a ON t.account_id = a.account_id
LEFT JOIN accounts ra ON t.related_account_id = ra.account_id
WHERE a.user_id = ? AND DATE(t.created_at) BETWEEN ? AND ?
ORDER BY t.created_at DESC
");
$stmt->execute([$userId,$from,$to]);

/* =======================
   TABLE
======================= */
$html = '
<table border="1" cellpadding="5">
<tr style="background-color:#1F2937;color:#fff;font-weight:bold;">
<th width="5%">#</th>
<th width="12%">ID</th>
<th width="12%">Type</th>
<th width="12%">Amount</th>
<th width="30%">Description</th>
<th width="14%">Account</th>
<th width="15%">Date</th>
</tr>';

$sn=1;
while($r=$stmt->fetch()){
$html.="<tr>
<td>$sn</td>
<td>{$r['transaction_id']}</td>
<td>{$r['type']}</td>
<td>₹".number_format($r['amount'],2)."</td>
<td>{$r['description']}</td>
<td>{$r['related_account']}</td>
<td>".date('Y-m-d H:i',strtotime($r['created_at']))."</td>
</tr>";
$sn++;
}
$html.="</table>";

$pdf->writeHTML($html, true, false, true, false, 'UTF-8');

/* =======================
   FOOTER NOTES
======================= */
$pdf->SetY(-40);
$pdf->SetFont('dejavusans','I',9);
$pdf->Line(10, $pdf->GetY(), 287, $pdf->GetY());
$pdf->Ln(4);
$pdf->MultiCell(0,6,
"This receipt is system-generated and digitally verifiable.\nScan QR or verify online.\nUnauthorized modification invalidates this document.",
0,'C');


logAdminAction(
    $pdo,
    $_SESSION['user_id'],
    'Report Download',
    'Downloaded transaction report PDF'
);

/* =======================
   OUTPUT
======================= */
$pdf->Output('transaction_receipt.pdf','D');
@unlink($qrFile);
exit;
